### ISSUE TITLE
NFT hack

### ISSUE THREAD

**Issue by pet3r-pan** [achadha235/niftycrate#1]
Just a small side note, we are also running the Untitled NFT hackathon that is ending on the 27th of Oct (6PM PST)

Feel free to submit your hack to this hackathon as well if you wish :)

https://medium.com/nfthack/untitled-nft-hack-submissions-e1418a3fbfda

**Comment by achadha235** [comment]
Very cool, thanks for the heads up! Will definitely submit as soon as I'm done.
