### ISSUE TITLE
Untitled NFT Submission Markdown

### ISSUE THREAD

**Issue by achadha235** [achadha235/niftycrate#2]
# NiftyCrates

### Team (include twitter/telegram contact)
- Abhi: Telegram @abhishek_c137 / Discord abhi#3948 
- https://www.linkedin.com/in/abhishek-chadha-53b09364
- https://twitter.com/achadha235

### One sentence description of what you built
Decentralized ERC-721 loot boxes built with a Top-down composable ERC-721

### Did you start working on this before the 8th of October?
I started programming on October 8th. Spent some time designing app / contracts from October 1 - 8th.
 
#### Link to a video demo (please keep to 5 minutes)
- https://www.youtube.com/watch?v=pu_pdAC7Yak&feature=youtu.be

#### Link to a presentation
https://docs.google.com/presentation/d/13NcaobQDCjwW61CNxtJ9vBzvIrsfzZOMaAickHM3460/edit?usp=sharing

#### Link to a working product/live demo
- Coming Soon!

#### Link to a github repo/more
- https://github.com/achadha235/niftycrate
- Crate Opener Math - https://drive.google.com/file/d/1D75BqJahzkD2ZGY-y4vQRWiQB9778fKP/view?usp=sharing

#### ETH Address to receive NFTs/ETH/DAI prizes and bounties 
- https://etherscan.io/address/0x02Ee97a13e434717e3FFa12758a235D1a1680775

**Comment by achadha235** [comment]
@pet3r-pan here is my submission for the Untitled NFT - hope its okay!

**Comment by pet3r-pan** [comment]
works!

**Comment by achadha235** [comment]
thanks @pet3r-pan was good fun 👍
